### PR TITLE
Compression Fixes #968

### LINKED ISSUE #968: Major - NPC Sale list
Each NPC sale list will update with previous NPC sale list opened. 

image
****

image

### PR DESCRIPTION
**Pull request by damianday**
Move CompressBytes/DecompressBytes to Functions.
Add new packet CompressedPacket.
Make use of compression with NPC goods, reduces packet size much!

### CODE REVIEW

**Comment by Suprcode** [comment]
You seem to be compressing a packet inside another packet. I dont understand why you wouldnt just build the compression in to all packets naturally, or have a new class certain packets inherit from to compress.

This method seems a tad messy and complicated to implement should any other packets was compression

**Comment by damianday** [comment]
Yeah it's a bit hacked together, I want the flexibility to be able to send and receive the compressed packet in chunks, leave it with me and I'll improve it tomorrow.

**Comment by Suprcode** [comment]
I would probably add a new class the packet can inherit from which overrides the read and write methods.

Then when someone wants to add a new packet that needs chunks/compression they dont need to do anything but change the packets base class

**Comment by damianday** [comment]
Forgot to mention the other reason it was written this way (sending as multiple packets) was due to the size limitation of 65535, but that could be addressed in a separate commit

**Comment by damianday** [comment]
This is looking a lot simpler now, just set the Compressed to true and it will do the rest.
DecompressPacket / CompressPacket can be overriden to provide custom compressing if required.

**Pull request merged**
