### PR TITLE
Character List

### PR DESCRIPTION
**Pull request by JevLOMCN**
Added a Character List which will display all Characters.

Before this the process of searching Characters was to either go through them individually using the Account Info Form or the Players Online Tab.

Also has a Filter By Item UID/Name box which allows you to quickly identify the owner of an Item.

image

### CODE REVIEW

**Comment by Jinspang** [comment]
I don't understand why you are doing this. Are you going to fill all the empty spaces in the Server's form? These functions can be completely added in the Account. I really don't understand why I have to write a form to operate it alone.

**Comment by JevLOMCN** [comment]
> I don't understand why you are doing this. Are you going to fill all the empty spaces in the Server's form? These functions can be completely added in the Account. I really don't understand why I have to write a form to operate it alone.

Explained pretty well in the PR Description

**Comment by CookieLOM** [comment]
All things like this are appreciated @JevLOMCN extra information is never a bad thing and if people aren't grateful that's there issue 😁

**Comment by JevLOMCN** [comment]
> All things like this are appreciated @JevLOMCN extra information is never a bad thing and if people aren't grateful that's there issue 😁

Alot of people get upset when it's not some massive new update.

Just out here trying to make GM lives easier 

#GMLivesMatter

**Pull request merged**
