### PR TITLE
Map Search

### PR DESCRIPTION
**Pull request by JevLOMCN**
- Added a Map Search option on the Map Info Form.

image

### CODE REVIEW

**Comment by Suprcode** [comment]
the remove all respawns button should be inside the respawns tab (next to the existing remove button)

**Comment by JevLOMCN** [comment]
> the remove all respawns button should be inside the respawns tab (next to the existing remove button)

The Remove all respawns button can work if you select multiple map indexes, I can move if you still want me to

**Comment by Suprcode** [comment]
actually i see your logic just deletes from all selected maps - i don't understand the need to delete respawns in bulk like that though?

Surely if anyone wants to redo spawns, they just delete them from 1 map, and add them back.

**Comment by JevLOMCN** [comment]
> actually i see your logic just deletes from all selected maps - i don't understand the need to delete respawns in bulk like that though?
> 
> Surely if anyone wants to redo spawns, they just delete them from 1 map, and add them back.

I agree that you'd probs not want to delete multiple map's respawn data but the way the code does it is by grabbing the selected index so if multiple are selected then it will do that. Would you like me to move it into the Respawns tab ?

**Comment by Suprcode** [comment]
in that case i don't think the button is needed at all. It seems very niche to want to clear out multiple maps at a time.

**Comment by JevLOMCN** [comment]
Button removed

**Pull request merged**
