### PR TITLE
Weather System

### PR DESCRIPTION
**Pull request by JevLOMCN**
Massive thanks to Win & TheDeath for helping.

There will be some further commits.

Database Version 110 Please back up your database before updating.

### CODE REVIEW

**Comment by JevLOMCN** [comment]
Hopefully that should do it [Weather Clean up](https://github.com/Suprcode/Crystal/pull/948/commits/e2edef59163247941b24e419acb6d591ca021ee0)

Weather Lib attached below.

[weather.zip](https://github.com/Suprcode/Crystal/files/15337004/weather.zip)

Video:
https://www.youtube.com/watch?v=37u6P_LX91k

**Comment by Suprcode** [comment]
image
still a few references like this one which need changing back

**Comment by JevLOMCN** [comment]
I did fork the latest source and then added the weather files in. So hopefully that should do it.

**Comment by Suprcode** [comment]
unfortunately not - the seems to have gone in the opposite direction now and even more things have reverted.

Take a look through the PR changes, several of the last commits have all been removed in this one.

**Comment by JevLOMCN** [comment]
I'll just repull.

**Comment by Suprcode** [comment]
Its not your PR, its your own forked code

https://github.com/JevLOMCN/Crystal/commit/2ab68acbb4ba3f33efcd660719f93cc6d0138578

You can see your own code has removed the last 3 commits

**Comment by JevLOMCN** [comment]
Yea but github desktop wasn't allowing me to repull stuff. I'll just re pr it.

**Pull request closed without merging**
